version: '3.9'
services:
  nli-api:
    build: 
      context: .
      dockerfile: .Dockerfile
      args:
        - github_user=${GITHUB_USERNAME}
        - github_key=${GITHUB_TOKEN}
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=80
    ports: 
      - "80:80"
    volumes:
      - type: bind
        target: /app/logs
        source: ./logs
        